In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('alegerian_forest.csv')

In [3]:
df.head()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0,0
1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0,0
2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0,0
3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0,0
4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0,0


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  243 non-null    int64  
 1   RH           243 non-null    int64  
 2   Ws           243 non-null    int64  
 3   Rain         243 non-null    float64
 4   FFMC         243 non-null    float64
 5   DMC          243 non-null    float64
 6   DC           243 non-null    float64
 7   ISI          243 non-null    float64
 8   BUI          243 non-null    float64
 9   FWI          243 non-null    float64
 10  Classes      243 non-null    int64  
 11  Region       243 non-null    int64  
dtypes: float64(7), int64(5)
memory usage: 22.9 KB


In [5]:
# independent & dependent features
X = df.drop('FWI', axis=1)
y = df['FWI']

In [6]:
X.head()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,Classes,Region
0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0,0
1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0,0
2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0,0
3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0,0
4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0,0


In [7]:
y.head()

0    0.5
1    0.4
2    0.1
3    0.0
4    0.5
Name: FWI, dtype: float64

In [8]:
# Train Test Split
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=10)

In [10]:
X_train.shape

(182, 11)

In [11]:
y_train.shape

(182,)

In [12]:
y_test.shape

(61,)

In [13]:
X_train.corr()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,Classes,Region
Temperature,1.000000,-0.669720,-0.334140,-0.353265,0.677623,0.487571,0.389471,0.602026,0.467013,0.546279,0.283242
RH,-0.669720,1.000000,0.204591,0.222707,-0.649486,-0.428679,-0.266198,-0.707446,-0.383706,-0.463607,-0.401123
Ws,-0.334140,0.204591,1.000000,0.128902,-0.174288,-0.006788,0.058934,0.004938,0.020047,-0.098821,-0.181108
Rain,-0.353265,0.222707,0.128902,1.000000,-0.566291,-0.319280,-0.312623,-0.364699,-0.327179,-0.386251,-0.035181
FFMC,0.677623,-0.649486,-0.174288,-0.566291,1.000000,0.608838,0.520211,0.743021,0.600643,0.774048,0.248338
DMC,0.487571,-0.428679,-0.006788,-0.319280,0.608838,1.000000,0.885047,0.690427,0.983489,0.591989,0.193025
DC,0.389471,-0.266198,0.058934,-0.312623,0.520211,0.885047,1.000000,0.536126,0.944205,0.500287,-0.063488
ISI,0.602026,-0.707446,0.004938,-0.364699,0.743021,0.690427,0.536126,1.000000,0.664122,0.752023,0.280281
BUI,0.467013,-0.383706,0.020047,-0.327179,0.600643,0.983489,0.944205,0.664122,1.000000,0.589880,0.096093
Classes,0.546279,-0.463607,-0.098821,-0.386251,0.774048,0.591989,0.500287,0.752023,0.589880,1.000000,0.231666


In [14]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i,j])>threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr   

In [15]:
corr_features = correlation(X_train, 0.85)

In [16]:
corr_features

{'BUI', 'DC'}

In [17]:
X_train.drop(corr_features, axis = 1, inplace = True)
X_test.drop(corr_features, axis = 1, inplace = True)

In [18]:
X_train.shape

(182, 9)

In [19]:
X_test.shape

(61, 9)

# Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [21]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [22]:
X_train_scaled

array([[-0.82246204, -0.13248758, -0.96126494, ..., -0.8800242 ,
        -1.0921406 , -1.        ],
       [-1.64946806,  1.26631775,  2.29867702, ..., -1.04641643,
        -1.0921406 , -1.        ],
       [ 1.38288736, -1.73112224, -0.96126494, ...,  1.66339986,
         0.91563303,  1.        ],
       ...,
       [ 0.28021266, -2.46382979, -0.96126494, ...,  2.25765782,
         0.91563303,  1.        ],
       [-0.54679336,  0.06734175, -0.59904916, ..., -0.59478038,
        -1.0921406 ,  1.        ],
       [-1.09813071,  1.06648841, -1.32348071, ..., -0.80871325,
        -1.0921406 , -1.        ]])

In [23]:
X_test_scaled

array([[-8.22462036e-01,  4.67000417e-01, -5.99049163e-01,
        -4.08099905e-01,  3.82324752e-01, -4.03032864e-01,
        -3.57077199e-01,  9.15633026e-01, -1.00000000e+00],
       [-8.22462036e-01, -9.31804908e-01,  1.21202970e+00,
        -4.08099905e-01,  7.70459017e-01, -2.40355537e-01,
         1.04537158e+00,  9.15633026e-01,  1.00000000e+00],
       [ 1.10721869e+00, -4.65536466e-01,  1.25382383e-01,
        -4.08099905e-01,  7.90534928e-01,  7.12468805e-01,
         8.31438717e-01,  9.15633026e-01,  1.00000000e+00],
       [-1.64946806e+00,  1.19970797e+00,  1.93646125e+00,
         2.68665770e+00, -1.90632902e+00, -8.98811384e-01,
        -1.02264611e+00, -1.09214060e+00, -1.00000000e+00],
       [-8.22462036e-01,  1.13309819e+00, -5.99049163e-01,
         6.59057892e-01, -1.89963705e+00, -9.60783698e-01,
        -1.04641643e+00, -1.09214060e+00,  1.00000000e+00],
       [ 5.55881339e-01, -3.32316911e-01,  1.25382383e-01,
        -4.08099905e-01,  7.36999167e-01,  1.022330

In [24]:
X_train

,Temperature,RH,Ws,Rain,FFMC,DMC,ISI,Classes,Region
1,29,61,13,1.3,64.4,4.1,1.0,0,0
2,26,82,22,13.1,47.1,2.5,0.3,0,0
149,37,37,13,0.0,92.5,27.2,11.7,1,1
208,36,54,14,0.0,91.0,65.9,10.0,1,1
103,29,88,13,0.0,71.0,2.6,1.2,0,0
...,...,...,...,...,...,...,...,...,...
64,34,69,13,0.0,85.0,8.2,4.0,1,0
15,29,89,13,0.7,36.1,1.7,0.0,0,0
228,33,26,13,0.0,93.9,21.2,14.2,1,1
125,30,64,14,0.0,79.4,5.2,2.2,0,1


# Linear Regression Model

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
linreg = LinearRegression()

In [27]:
linreg.fit(X_train_scaled, y_train)

LinearRegression()

In [28]:
y_pred = linreg.predict(X_test_scaled)

In [29]:
y_pred

array([ 4.34621195, 10.67373995, 12.9753663 ,  0.4135101 , -1.02488616,
       13.19946919,  3.20191627, 17.02853003,  6.68493498,  1.65329755,
        1.3394002 ,  7.23828016, 10.57153511, 11.26162371,  6.59652141,
       14.37784468,  0.16775376, 20.96435475,  6.07130094,  2.35717789,
        4.8009065 ,  1.79600584, 14.64159015,  1.16028556,  0.33934839,
        9.50375339,  1.69970775,  1.80949787,  0.89111593,  1.79404326,
        7.85801687,  5.14426939,  3.87443408,  8.34453306, 16.35964858,
        0.16473317,  1.322402  ,  0.5955332 , 13.91854575,  1.07036698,
       14.35427028, 10.41756323, 11.41865597,  7.73734617,  9.8352819 ,
       25.01125817,  0.65939849, 13.88789197, -0.22922468,  2.75122621,
        6.52145191, 22.97782455,  3.20799937,  8.26047586, -0.43174741,
       25.46846083, 11.89850511,  4.18616184,  0.2316082 ,  4.84985639,
       11.73074393])

In [30]:
from sklearn.metrics import mean_absolute_error

In [31]:
mae = mean_absolute_error(y_test, y_pred)

In [32]:
mae 

0.6097576371929294

In [33]:
from sklearn.metrics import r2_score

In [34]:
score = r2_score(y_test, y_pred)

In [35]:
print(score)

0.9845036003441805


# Lasso Regression - L1 regularization

In [36]:
from sklearn.linear_model import Lasso

In [37]:
lasso = Lasso()

In [38]:
lasso.fit(X_train_scaled, y_train) 

Lasso()

In [39]:
y_pred = lasso.predict(X_test_scaled)

In [40]:
y_pred

array([ 4.40903932, 10.34980871, 12.42143752,  0.31472754,  0.03366997,
       12.53462945,  3.93443056, 15.72125148,  7.24172698,  2.57424406,
        3.26269706,  6.97799523, 10.14729144, 10.30019217,  6.61388214,
       12.8252594 ,  0.19883935, 19.14686136,  5.87884421,  1.84426329,
        4.58256845,  3.03301062, 13.04058726,  3.01359487,  1.37713699,
        9.59144612,  2.96074013,  3.45833819,  2.15161274,  2.5993233 ,
        7.48037949,  5.81075359,  4.40903932,  7.84894342, 14.38850512,
        0.87057286,  2.97118981,  2.3660633 , 12.50179678,  2.21612981,
       13.57553321, 10.12848201, 10.45612451,  7.6048984 ,  9.09802793,
       22.47532812,  2.38965893, 12.50537034,  1.76781293,  3.12381956,
        6.33821709, 20.87709542,  3.46730426,  7.82595412, -0.36536572,
       22.60193696, 11.55257926,  5.58821426,  2.0440843 ,  4.7241422 ,
       10.70610399])

In [41]:
y_test

46      3.6
225    10.3
180    13.2
116     0.1
124     0.1
       ... 
148    12.0
232     3.8
136     0.6
49      4.0
58     11.9
Name: FWI, Length: 61, dtype: float64

In [42]:
from sklearn.metrics import mean_absolute_error

In [43]:
mae = mean_absolute_error(y_test, y_pred)

In [44]:
mae

1.1914563426451286

In [45]:
from sklearn.metrics import r2_score

In [46]:
score = r2_score(y_test, y_pred)

In [47]:
print(score)

0.9507719280238188


# Ridge Regression - L2 regularization

In [48]:
from sklearn.linear_model import Ridge 

In [49]:
ridge = Ridge()

In [50]:
ridge.fit(X_train_scaled, y_train)

Ridge()

In [51]:
y_pred = ridge.predict(X_test_scaled)

In [52]:
y_pred

array([ 4.38902715, 10.68518817, 12.97272743,  0.40409601, -1.0629079 ,
       13.20204776,  3.24433029, 17.00254123,  6.71625321,  1.70838684,
        1.36420161,  7.25809378, 10.62858843, 11.25191047,  6.70053677,
       14.36324446,  0.12449144, 20.8473788 ,  6.11098036,  2.36035216,
        4.89732912,  1.83340874, 14.63618913,  1.17318549,  0.35779863,
        9.52035641,  1.71855017,  1.85514035,  0.92290726,  1.77201167,
        7.87720498,  5.2008456 ,  3.99418901,  8.36068858, 16.37079985,
        0.14587179,  1.39203519,  0.64760432, 13.90254704,  1.13719108,
       14.34276351, 10.43456412, 11.41713804,  7.80012668,  9.856387  ,
       24.87012717,  0.71523685, 13.86705538, -0.18264348,  2.79236687,
        6.54580627, 22.85404525,  3.26533149,  8.26918985, -0.49160457,
       25.38519703, 11.89919864,  4.2123393 ,  0.20022956,  4.91681443,
       11.72006434])

In [53]:
y_test

46      3.6
225    10.3
180    13.2
116     0.1
124     0.1
       ... 
148    12.0
232     3.8
136     0.6
49      4.0
58     11.9
Name: FWI, Length: 61, dtype: float64

In [54]:
from sklearn.metrics import mean_absolute_error

In [55]:
mae = mean_absolute_error(y_test, y_pred)

In [56]:
mae

0.6329143779561464

In [57]:
from sklearn.metrics import r2_score

In [58]:
score = r2_score(y_test, y_pred)

In [59]:
print(score)

0.983692581331822


# Elastic net regression 

In [60]:
from sklearn.linear_model import ElasticNet 

In [61]:
elastic = ElasticNet()

In [62]:
elastic.fit(X_train_scaled, y_train)

ElasticNet()

In [63]:
y_pred = elastic.predict(X_test_scaled)

In [64]:
y_pred

array([ 5.82396345, 10.27053097, 12.10223255,  0.12768482,  0.05161994,
       12.20896368,  4.14350219, 14.7028492 ,  7.92199552,  3.53344367,
        3.89927172,  7.84512915, 11.03559894, 10.09868279,  8.32136022,
       12.27438249,  0.05721599, 16.76011879,  7.10600454,  1.49065084,
        6.47641188,  3.55782332, 12.53185563,  3.63989962,  1.70209711,
        9.85583685,  3.57088443,  3.6183658 ,  2.80831773,  3.15710569,
        8.43439995,  7.2466855 ,  6.85786587,  8.45163079, 13.37092323,
        0.88638068,  3.75806352,  3.0004756 , 11.94431915,  3.43177879,
       13.07506573, 10.51052786, 10.67680276,  9.35931479,  9.53018706,
       19.45052915,  3.15567491, 12.35305697,  2.07456895,  4.658037  ,
        7.29424925, 18.82415059,  5.24323461,  8.78363483, -0.55447175,
       20.08200463, 11.48042586,  5.65615564,  1.55272788,  6.39670675,
       10.50259845])

In [65]:
y_test

46      3.6
225    10.3
180    13.2
116     0.1
124     0.1
       ... 
148    12.0
232     3.8
136     0.6
49      4.0
58     11.9
Name: FWI, Length: 61, dtype: float64

In [66]:
from sklearn.metrics import mean_absolute_error

In [67]:
mae = mean_absolute_error(y_test, y_pred)

In [68]:
mae

1.8874633328409454

In [69]:
from sklearn.metrics import r2_score

In [70]:
score = r2_score(y_test, y_pred)

In [71]:
print(score)

0.8803445600259008


In [72]:
import pickle
pickle.dump(scaler, open('scaler.pkl', 'wb'))
pickle.dump(ridge, open('ridge.pkl', 'wb'))